name: vilarc
favicon: null
layout_spectrum: 0.9774748724885285
typography_spectrum: 0.08607787732034922
title: Unboxing Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2117347721941769
  lightness: 0.5655330342706293
  saturation: 0.46810178621672094
  rhythmicContrast: 0.6899841448757797
purpose: []
